baseurl = "https://tectalks.com/"
title = "Tectalks"
author = "Vibin Kurusingal"
canonifyurls = true
languagecode = "en"
theme = "zen"
copyright = "© 2026 Tectalks"
googleAnalytics = "G-LZKDZ0ND0S"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = false
  logoWidth = 200
  disableWebFonts = false
  poweredby = false
  submitted= true
  feedlinks = false
  cookieConsent= true
  favicon= "apple-touch-icon.png"
#  sidebar= true

[[menu.main]]
    name = "About"
    url  = "/about"

[[menu.main]]
    name = "Instagram"
    url  = "https://instagram.com/vibin.aero"
